[![Open in Visual Studio Code](https://classroom.github.com/assets/open-in-vscode-2e0aaae1b6195c2367325f4f02e2d04e9abb55f0b24a779b69b11b9e10269abc.svg)](https://classroom.github.com/online_ide?assignment_repo_id=16926468&assignment_repo_type=AssignmentRepo)

= SAÉ 3.01 2023-2024
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank

[.correction]
!Correction!

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae3-01-template

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

TIP: Pensez à mettre à jour les infos dans ce fichier pour que les badges pointent sur les résultats effectifs de vos intégrations continue ou sur la bonne licence logicielle.

WARNING: Ce dépôt présente le projet à développer dans le cadre de la SAÉ 3.01 du BUT1 Informatique de l'IUT de Blagnac.

Ce fichier `README.adoc` (dont vous lisez sûrement le rendu HTML automatiquement effectué par GitHUb), fait partie du dépôt initial cloné à partir du lien GitHub classroom qui vous a été donné en cours (https://classroom.github.com/a/fePVlfpN).
Vous trouverez le dépôt "template" qui a servi de base ici : https://github.com/IUT-Blagnac/sae3-01-template. En complément du cours Moodle de la SAE 3.01 (cf. <<liensUtiles>>), ce dépôt template vous permet d'accéder à des exemples d'https://github.com/IUT-Blagnac/sae3-01-template/issues[issues], de https://github.com/IUT-Blagnac/sae3-01-template/releases[releases], ou d'autres artefacts à venir.

toc::[]

== Equipe

Projet est réalisé par::

- https://github.com/Ducry-PL[Ducry Pierre-Louis] : Scrum Master
- https://github.com/Spiritdev31[Da Chao Romain] : Product Owner
- https://github.com/Mialiso[Razafinirina Mialisoa] : Développeur
- https://github.com/MatteoPel[Pellegatta Matteo] : Développeur

Tuteur/tutrice enseignant(e) de l'équipe:: mailto:jean-michel.bruel@univ-tlse2.fr[JMB]

== Présentation du client : Brickolo SARL
___Brickolo Sarl___, fondée en 1924 à Blagnac, est un acteur majeur dans la conception de briques de jeu en plastique. Initialement centrée sur les jouets en bois, l'entreprise a su évoluer pour répondre aux attentes de ses clients et s'adapter aux enjeux modernes.

Depuis 2021, sous la direction d'Anna Müller, Brickolo s'engage dans une transition écologique en utilisant des plastiques recyclés pour ses produits. Parallèlement, l'entreprise investit dans une transformation numérique, avec ___une refonte complète de son site internet___, visant à :

- Moderniser l'expérience utilisateur.
- Offrir une interface sobre, intuitive et accessible.
- Mettre en avant ses valeurs écologiques.
- Renforcer sa présence en ligne pour répondre aux besoins d’un secteur en pleine mutation.

== Contexte général

TIP: Cette partie de votre `README.adoc` peut être supprimée ou mise ailleurs.

=== Dépôt initial

Ce dépôt initial a été créé pour que tous les groupes de 2ème année aient les mêmes informations de départ.

Vous y trouverez des fichiers qui peuvent être supprimés s'ils ne vous sont pas utiles :

- `.gitignore` => un fichier minimaliste des éléments à ne pas pousser en général sur vos dépôts (utiliser la commande `git add -f` pour forcer l’ajout d’un fichier Jar qui ne bougera plus, pour archive par exemple).
- `.github` => le répertoire qui contient des éléments de gestion de projet :
** `workflows` => le repertoire qui contient les actions à lancer à chaque push sur votre repo. 
*** `blank.yml` => un exemple bidon mais dont vous pourrez vérifier l’exécution correcte (1er tag)
** `ISSUE_TEMPLATE` => le répertoire qui contient quelques templates pour vos issues.
*** `us.yml` => Exemple de template pour les User Stories
*** `bug.yml` => Exemple de template pour les issues de bug report

TIP: Adaptez ces fichiers à votre projet et à votre organisation. Et inspirez-vous en pour en ajouter.

[[liensUtiles]]
=== Liens utiles

- Le https://webetud.iut-blagnac.fr/course/view.php?id=841[cours Moodle] sur la SAE
- Le dépôt https://github.com/IUT-Blagnac/sae3-01-template[template] qui sert de base à tous les dépôts étudiants.
- Le lien https://classroom.github.com/a/OUF7gxEa[classroom] si besoin.

TIP: Pensez à utiliser les salons Discord dédiés pour poser vos questions.

== Réalisations 

https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/blob/master/Documentation/GPO/CahierDeRecettes-2A7%20(1).pdf[Cahier de recette] +
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/blob/master/Documentation/GPO/DocTechnique.adoc[Doc Technique] + 
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/blob/master/Documentation/GPO/DocUtilisateur.adoc[Doc Utilisateur] + 
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/blob/master/Documentation/GPO/DocConception.adoc[Document de Conception] +

[cols="1,3"]
|===
| Sprints | Documents 

| Sprint#1 |

https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/milestone/1[Tâches Sprint 1]

| Sprint #2 |
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/milestone/2[Tâches Sprint 2]
| Sprint #3 |
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/milestone/3[Tâches Sprint 3]
| Sprint #4 |
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/milestone/4[Tâches Sprint 4]
| Sprint #5 |
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/milestone/5[Tâches Sprint 5]
| Sprint #6 |
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/milestone/5[Tâches Sprint 6]
| Sprint #7 |
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/milestone/5[Tâches Sprint 7]
| Sprint #8 |
https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/milestone/5[Tâches Sprint 8]


|===


https://github.com/orgs/IUT-Blagnac/projects/273[Backlog Produit]


Livraison Finale du Site Web : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/tree/master/PHP[Dossier WebSite]

Droit : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/blob/master/Documentation/Fiche_Conseil.adoc[Fiche de conseils juridiques et de sécurité]

Lien du site web : http://193.54.227.208/~R2024SAE3003/index.php[Brickolo]

|===
| Semaine | ODJ | Bilan 
| 49 | https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/blob/master/R%C3%A9unions/Semaine%2049/ODJ_02-12-24.pdf[ODJ-S49]|https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/blob/master/R%C3%A9unions/Semaine%2049/CR_02_12-24.pdf[CR-S49]
| 50 |https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/blob/master/R%C3%A9unions/Semaine%2050/ODJ_09-12-24.pdf[ODJ-S50]|https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/blob/master/R%C3%A9unions/Semaine%2050/CR_11-12-24.pdf[CR-S50]
| 51 |https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/blob/master/R%C3%A9unions/Semaine%2051/ODJ_16-12-24.pdf[ODJ-S51]|https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/blob/master/R%C3%A9unions/Semaine%2051/CR%20S50[CR-S51]
| 02 |https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/blob/8da61e1e0fc80e627eabce25368a56659025074a/R%C3%A9unions/Semaine%202/ODJ_07-01-25.pdf[ODJ-S02]|https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/tree/4f1f1b17c5b57de2c1a4ce89f4d6a7ea564765e9/R%C3%A9unions/Semaine%202/CR_07-01-25.pdf[CR-S02] 
| 03 |https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/blob/master/R%C3%A9unions/Semaine%203/ODJ%20POST%20MORTEM.pdf[ODJ-03 PostMortem] |
|===

=== Retour communication semaine 48

J'ai l'ODJ mais pas le compte rendu ! ODJ : Préciser qui est responsable de chaque rubrique, combien de temps on y consacre, qui fera le CR. 
note : 0,3/3

=== Retour communication semaine 49 EP
ODJ : manque toujours qui est resp de chaque rubrique et quel temps on y consacre ! CR : Préciser ABS/Present, préciser qui a rédigé le CR. Manque CR réunion client et analyse réussites et difficultés.
note : 1,95/3
note appel offre : 12,65/20

=== Retour communication semaine 50 par EP
ODJ et CR: cf remarques semaine 49 !!! Merci d'en prendre compte !
note : 2,06/3

=== Retour communication semaine 51 par EP
Responsable de chaque item toujours non indiqué ! Pas de CR semaine 51
0,4/3

== Gestion de projet & Qualité

Chaque sprint (semaine) vous devrez livrer une nouvelle version de votre application (release).
Utilisez pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

De plus ce fichier `README.adoc` devra être à jour des informations suivantes :

- Version courante : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/releases
- Changelog : https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2a7/blob/master/Changelog.md

== Planning des Sprints

|===
| Sprint   | Lundi AM | Lundi PM | Mardi AM | Mardi PM | Mercredi AM | Mercredi PM | Jeudi AM  | Jeudi PM  | Vendredi AM | Vendredi PM |
| Sprint 1 | Télétravail |          |          | Télétravail |             |             |           |           | Télétravail |        Télétravail     |
| Sprint 2 |          |          | Télétravail | Télétravail | Télétravail possible | Télétravail | Télétravail |           | |       Télétravail      |
| Sprint 3 | Télétravail | Télétravail |          |          | Télétravail |             | Télétravail | Télétravail |  |             |
| Sprint 4 |          | Télétravail |          |          | Télétravail |             |           |           | Télétravail |             |
| Sprint 5 | Télétravail |          |          | Télétravail |             |             |           | Télétravail | |             |
| Sprint 6 |          | Télétravail | Télétravail |          |             | Télétravail | Télétravail |           | Télétravail | Télétravail  |
|===

==== Cycle de vie de la version

Chaque nouvelle version de votre application doit être :
- Nommée version X.Y.Z
- Taggée en version X.Y.Z où X = majeure, Y = mineure, Z = patch
- Décrite dans un `Changelog.md` incluant l’historique des versions.

==== Bonnes pratiques

- Lancement continu des tests unitaires avec https://github.com/actions[GitHub Actions]
- Tests fonctionnels réguliers de votre application
- Versionner vos versions dans le fichier `Changelog.md` avec la norme Semver : https://semver.org/lang/fr/

==== Liens utiles

- https://github.com/actions[GitHub Actions]
- https://semver.org/lang/fr/
- https://github.com/greenkeeperio/greenkeeper[Greenkeeper]

=== Dépôt et Version

Chaque groupe doit pousser régulièrement ses avancées.

- Lors de la **création du projet**, commencez par créer une branche pour votre fonctionnalité.
- Poussez chaque nouvelle version sur votre dépôt.

=== Bonus

- L'équipe à réaliser un test complet.
- Ajouter l'intégration continue via Github Actions.
